### ISSUE TITLE
Doesn't compile against openssl-1.1

### ISSUE THREAD

**Issue by BlackLotus** [Lekensteyn/dmg2img#4]
> cc -g -O2 -Wall -o vfdecrypt vfdecrypt.c -lcrypto 
vfdecrypt.c: In function ‘apple_des3_ede_unwrap_key’:
vfdecrypt.c:215:18: error: storage size of ‘ctx’ isn’t known
   EVP_CIPHER_CTX ctx;
                  ^~~
vfdecrypt.c:215:18: warning: unused variable ‘ctx’ [-Wunused-variable]
vfdecrypt.c: In function ‘unwrap_v2_header’:
vfdecrypt.c:282:18: error: storage size of ‘ctx’ isn’t known
   EVP_CIPHER_CTX ctx;
                  ^~~
vfdecrypt.c:282:18: warning: unused variable ‘ctx’ [-Wunused-variable]
vfdecrypt.c: In function ‘main’:
vfdecrypt.c:449:3: warning: implicit declaration of function ‘HMAC_CTX_init’ [-Wimplicit-function-declaration]
   HMAC_CTX_init(&hmacsha1_ctx);
   ^~~~~~~~~~~~~
vfdecrypt.c:333:18: warning: variable ‘oflag’ set but not used [-Wunused-but-set-variable]
   int iflag = 0, oflag = 0, pflag = 0, kflag = 0, verbose = 0;
                  ^~~~~
vfdecrypt.c:333:7: warning: variable ‘iflag’ set but not used [-Wunused-but-set-variable]
   int iflag = 0, oflag = 0, pflag = 0, kflag = 0, verbose = 0;
       ^~~~~
vfdecrypt.c: At top level:
vfdecrypt.c:186:10: error: storage size of ‘hmacsha1_ctx’ isn’t known
 HMAC_CTX hmacsha1_ctx;

With openssl you cannot do this anymore
>   EVP_CIPHER_CTX ctx;

should become probably something like this
>    EVP_CIPHER_CTX *ctx;
>    ctx=EVP_CIPHER_CTX_new();
>    ...
>    EVP_CIPHER_CTX_free(ctx)

But there need to be some more changes.

**Comment by Lekensteyn** [comment]
Hi Thomas, I pushed a patch, can you check it?

**Comment by BlackLotus** [comment]
Works thank you
