### ISSUE TITLE
Does not work on x64 systems

### ISSUE THREAD

**Issue by floradu88** [Lekensteyn/dmg2img#5]
Can you create a release that will work on x64 OS?

**Comment by Lekensteyn** [comment]
Can you provide more details? I have only tested it on x64 on Linux (Arch Linux, Ubuntu 16.04, 14.04, ...).

**Comment by Lekensteyn** [comment]
No response, assuming no problem.

**Comment by floradu88** [comment]
Yes, I stopped using it found another tool to do this. I was using it on win10x64

**Comment by Lekensteyn** [comment]
This utility is not tested at all with Windows, how were you trying to build it anyway?
